name: CI-PR
on:
  push: null
jobs:
  clang-format:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: clang-format
      run: 'docker run --rm -v ${PWD}:/src ghcr.io/wiiu-env/clang-format:13.0.0-2 -r ./source --exclude
        ./source/elfio --exclude ./source/utils/json.hpp

        '
      id: _bre_clang_format
    - name: build binary with logging
      run: 'docker build . -t builder

        docker run --rm -v ${PWD}:/project builder make DEBUG=VERBOSE

        docker run --rm -v ${PWD}:/project builder make clean

        docker run --rm -v ${PWD}:/project builder make DEBUG=1

        '
    - name: create version.h
      run: 'git_hash=$(git rev-parse --short "${{ github.event.pull_request.head.sha }}")

        cat <<EOF > ./source/version.h

        #pragma once

        #define MODULE_VERSION_EXTRA " (nightly-$git_hash)"

        EOF

        '
      if: '!cancelled() && steps._bre_clang_format.conclusion == ''success'''
    - name: build binary
      run: 'docker build . -t builder

        docker run --rm -v ${PWD}:/project builder make

        '
      if: '!cancelled() && steps._bre_clang_format.conclusion == ''success'''
    - uses: actions/upload-artifact@master
      with:
        name: binary
        path: '*.wms'
      if: '!cancelled() && steps._bre_clang_format.conclusion == ''success'''
